executable(
  'vala-toml-decoder',
  'vala-toml-decoder.vala',
  dependencies: vala_toml_internal_dep,
  vala_args: ['--pkg', 'gee-0.8'],
  install: false,
)

executable(
  'vala-toml-encoder',
  'vala-toml-encoder.vala',
  dependencies: vala_toml_internal_dep,
  vala_args: ['--pkg', 'gee-0.8'],
  install: false,
)
